// Centralizes generation contracts so prompts, schemas, templates, and validators stay in sync.
export const SUPPORTED_NAVIGATION_TYPES = ["stack", "tabs"] as const;

export type SupportedNavigationType =
  (typeof SUPPORTED_NAVIGATION_TYPES)[number];

export const PATH_ALIAS = {
  importPrefix: "@/",
  sourcePrefix: "src/",
  resolvedPrefix: "./src/",
} as const;

export const ICON_CONTRACT = {
  packageName: "@expo/vector-icons",
  defaultImportName: "Feather",
  defaultImportPath: "@expo/vector-icons/Feather",
} as const;

export const VECTOR_ICON_IMPORT_PATHS: Record<string, string> = {
  Ionicons: "@expo/vector-icons/Ionicons",
  MaterialIcons: "@expo/vector-icons/MaterialIcons",
  FontAwesome: "@expo/vector-icons/FontAwesome",
  AntDesign: "@expo/vector-icons/AntDesign",
};

export const TEMPLATE_PACKAGE_SCRIPTS = {
  start: "expo start",
  web: "expo start --web",
  typecheck: "tsc --noEmit",
  "export:web": "expo export --platform web",
} as const;

export const TEMPLATE_PACKAGE_DEPENDENCIES = {
  expo: "~55.0.9",
  "expo-router": "~55.0.8",
  "expo-status-bar": "~55.0.4",
  "expo-linking": "~55.0.9",
  "expo-constants": "~55.0.9",
  react: "19.2.0",
  "react-dom": "19.2.0",
  "react-native": "0.83.4",
  "react-native-web": "~0.21.0",
  "react-native-safe-area-context": "~5.6.2",
  "react-native-screens": "~4.23.0",
  "react-native-gesture-handler": "~2.30.0",
  "react-native-reanimated": "4.2.1",
  "@expo/vector-icons": "^14.0.0",
  "@react-native-async-storage/async-storage": "2.2.0",
} as const;

export const TEMPLATE_PACKAGE_DEV_DEPENDENCIES = {
  "@types/react": "~19.2.2",
  typescript: "~5.9.2",
} as const;

export const REQUIRED_TEMPLATE_FILES = [
  "app.json",
  "tsconfig.json",
  "babel.config.js",
  "metro.config.js",
  "expo-env.d.ts",
  ".gitignore",
  "app/_layout.tsx",
] as const;

export const AUTO_GENERATED_PLAN_FILES = [
  "app/_layout.tsx",
  "app/(tabs)/_layout.tsx",
] as const;

/** Known-safe extra dependencies that LLM can request. Anything else gets verified against npm registry. */
export const SAFE_EXTRA_DEPENDENCIES = new Set([
  "zustand",
  "react-native-svg",
  "expo-linear-gradient",
  "expo-haptics",
  "expo-clipboard",
  "expo-image-picker",
  "expo-camera",
  "expo-location",
  "expo-sensors",
  "expo-notifications",
  "expo-av",
  "expo-file-system",
  "expo-secure-store",
  "expo-font",
  "expo-splash-screen",
  "expo-blur",
  "expo-brightness",
  "expo-battery",
  "expo-device",
  "expo-image",
  "expo-maps",
  "expo-crypto",
  "expo-local-authentication",
  "expo-sharing",
  "expo-web-browser",
  "expo-calendar",
  "expo-contacts",
  "expo-barcode-scanner",
  "react-native-maps",
  "react-native-chart-kit",
  "react-native-calendars",
  "react-native-gifted-charts",
  "react-native-modal",
  "react-native-image-zoom-viewer",
  "lottie-react-native",
  "date-fns",
  "dayjs",
  "uuid",
  "lodash",
  "axios",
  "async-storage",
  "@react-native-async-storage/async-storage",
  "@react-native-community/datetimepicker",
  "@react-native-community/slider",
  "react-native-element-dropdown",
  "burnt",
]);

export const MAX_DEPENDENCY_CONTEXT_FILES = 12;
export const MAX_DEPENDENCY_CONTEXT_CHARS = 18000;

export const isSupportedNavigationType = (
  value: string
): value is SupportedNavigationType =>
  SUPPORTED_NAVIGATION_TYPES.includes(value as SupportedNavigationType);

export const isAutoGeneratedPlanFile = (filePath: string): boolean =>
  AUTO_GENERATED_PLAN_FILES.includes(
    filePath as (typeof AUTO_GENERATED_PLAN_FILES)[number]
  );

export const isProjectFilePath = (value: string): boolean =>
  value.startsWith("app/") || value.startsWith("src/");

export const isAliasImport = (specifier: string): boolean =>
  specifier.startsWith(PATH_ALIAS.importPrefix);

export const isRelativeImport = (specifier: string): boolean =>
  specifier.startsWith("./") || specifier.startsWith("../");

export const isLocalProjectImport = (specifier: string): boolean =>
  isAliasImport(specifier) || isRelativeImport(specifier);

export const normalizeAliasSpecifier = (specifier: string): string =>
  specifier.replace(`${PATH_ALIAS.importPrefix}src/`, PATH_ALIAS.importPrefix);

export const getBareModuleName = (specifier: string): string => {
  if (specifier.startsWith("@")) {
    const [scope, name] = specifier.split("/");
    return name ? `${scope}/${name}` : specifier;
  }

  return specifier.split("/")[0];
};

export const getNavigationLayoutPath = (
  navigationType: SupportedNavigationType
): string =>
  navigationType === "tabs" ? "app/(tabs)/_layout.tsx" : "app/_layout.tsx";
