// Durable generation checkpoint + plan — single source of truth for resume across projects.
import fs from "fs";
import path from "path";
import { atomicWriteFileSync } from "./atomic-write.js";
import type { AppPlan } from "../schemas/app-plan.schema.js";
import { getProjectPath, readFile as readProjectFile } from "../services/file-manager.js";
import { stripAutoGeneratedPlanFilesIfNeeded } from "./generation-contract.js";
import { savePlanBlueprint } from "./plan-artifact.js";
import { warnCaught } from "./catch-log.js";

const STATE_DIR = ".appfactory";
const STATE_FILE = "generation-state.json";
const LEGACY_PLAN_FILE = "plan.json";
const EOF_MARKER = "// EOF";

export type GenerationCheckpoint =
  | "planned"
  | "scaffolded"
  | "codegen"
  | "shipped";

export interface ProjectGenerationState {
  version: 1;
  plan: AppPlan;
  checkpoint: GenerationCheckpoint;
  savedAt: string;
}

export type ResumeMode = "codegen" | "ship";

export interface ProjectResumeStatus {
  canResume: boolean;
  /** codegen = missing files; ship = all files on disk but preview never shipped */
  resumeMode: ResumeMode | null;
  hasSavedPlan: boolean;
  checkpoint: GenerationCheckpoint | null;
  missingFileCount: number;
  totalPlanFiles: number;
}

const statePath = (projectName: string): string =>
  path.join(getProjectPath(projectName), STATE_DIR, STATE_FILE);

const legacyPlanPath = (projectName: string): string =>
  path.join(getProjectPath(projectName), STATE_DIR, LEGACY_PLAN_FILE);

const readJson = <T>(filePath: string): T | null => {
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
  } catch (error) {
    warnCaught("generation-state", error, `read JSON state ${filePath}`);
    return null;
  }
};

const normalizeLoadedState = (
  projectName: string,
  state: ProjectGenerationState,
): ProjectGenerationState => {
  if (!stripAutoGeneratedPlanFilesIfNeeded(state.plan)) {
    return state;
  }
  const migrated: ProjectGenerationState = {
    ...state,
    savedAt: new Date().toISOString(),
  };
  persistState(projectName, migrated);
  savePlanBlueprint(projectName, migrated.plan);
  return migrated;
};

const migrateLegacyPlan = (projectName: string): ProjectGenerationState | null => {
  const legacy = readJson<AppPlan>(legacyPlanPath(projectName));
  if (!legacy) return null;
  stripAutoGeneratedPlanFilesIfNeeded(legacy);
  const state: ProjectGenerationState = {
    version: 1,
    plan: legacy,
    checkpoint: "scaffolded",
    savedAt: new Date().toISOString(),
  };
  persistState(projectName, state);
  savePlanBlueprint(projectName, legacy);
  return state;
};

const persistState = (projectName: string, state: ProjectGenerationState): void => {
  atomicWriteFileSync(statePath(projectName), JSON.stringify(state, null, 2));
};

export const loadGenerationState = (projectName: string): ProjectGenerationState | null => {
  const current = readJson<ProjectGenerationState>(statePath(projectName));
  if (current?.version === 1 && current.plan) {
    return normalizeLoadedState(projectName, current);
  }
  const migrated = migrateLegacyPlan(projectName);
  return migrated ? normalizeLoadedState(projectName, migrated) : null;
};

export const saveGenerationState = (
  projectName: string,
  plan: AppPlan,
  checkpoint: GenerationCheckpoint,
): void => {
  savePlanBlueprint(projectName, plan);
  persistState(projectName, {
    version: 1,
    plan,
    checkpoint,
    savedAt: new Date().toISOString(),
  });
};

export const advanceGenerationCheckpoint = (
  projectName: string,
  checkpoint: GenerationCheckpoint,
): void => {
  const state = loadGenerationState(projectName);
  if (!state) return;
  persistState(projectName, { ...state, checkpoint, savedAt: new Date().toISOString() });
};

/**
 * Structural completeness heuristic — true when the file PARSES as a finished module
 * even though it has no `// EOF` marker. We strip comments and string/template
 * literals, then require balanced braces/parens/brackets and at least one `export`.
 *
 * Why: a genuinely truncated file is cut mid-construct, so its braces don't balance →
 * this returns false and the heal loop still rescues it. But a COMPLETE file that
 * merely omitted the `// EOF` comment (local models drop trailing meta-comments, and
 * the polish stage strips the marker) is now recognized as done — instead of being
 * "continued" (which appends garbage onto working code) or, on resume, regenerated
 * from scratch.
 */
export const isStructurallyComplete = (content: string | null | undefined): boolean => {
  if (!content || content.trim().length < 20) return false;

  const stripped = content
    .replace(/\/\*[\s\S]*?\*\//g, "")     // block comments
    .replace(/\/\/[^\n]*/g, "")            // line comments
    .replace(/"(?:[^"\\]|\\.)*"/g, '""')   // double-quoted strings
    .replace(/'(?:[^'\\]|\\.)*'/g, "''")   // single-quoted strings
    .replace(/`(?:[^`\\]|\\.)*`/g, "``")   // template literals (naive)
    .replace(/\/(?:\\.|\[(?:\\.|[^\]\n\\])*\]|[^/\n\\])+\/[gimsuy]*/g, "//"); // regex literals (so /[}{]/ braces don't skew the count)

  if (!/\bexport\b/.test(stripped)) return false;

  let curly = 0;
  let paren = 0;
  let square = 0;
  for (const ch of stripped) {
    if (ch === "{") curly++;
    else if (ch === "}") curly--;
    else if (ch === "(") paren++;
    else if (ch === ")") paren--;
    else if (ch === "[") square++;
    else if (ch === "]") square--;
    if (curly < 0 || paren < 0 || square < 0) return false; // closed something never opened
  }
  return curly === 0 && paren === 0 && square === 0;
};

export const isPlanFileComplete = (content: string | null | undefined): boolean =>
  Boolean(content?.trim() && (content.includes(EOF_MARKER) || isStructurallyComplete(content)));

export const listMissingPlanFiles = (projectName: string, plan: AppPlan): string[] =>
  plan.files
    .filter((file) => !isPlanFileComplete(readProjectFile(projectName, file.path)))
    .map((file) => file.path);

export const getProjectResumeStatus = (projectName: string): ProjectResumeStatus => {
  const state = loadGenerationState(projectName);
  if (!state) {
    return {
      canResume: false,
      resumeMode: null,
      hasSavedPlan: false,
      checkpoint: null,
      missingFileCount: 0,
      totalPlanFiles: 0,
    };
  }

  const missing = listMissingPlanFiles(projectName, state.plan);
  const canResumeCodegen =
    state.checkpoint !== "shipped" && missing.length > 0;
  const canRetryShip =
    state.checkpoint !== "shipped" && missing.length === 0;
  const canResume = canResumeCodegen || canRetryShip;

  return {
    canResume,
    resumeMode: canResumeCodegen ? "codegen" : canRetryShip ? "ship" : null,
    hasSavedPlan: true,
    checkpoint: state.checkpoint,
    missingFileCount: missing.length,
    totalPlanFiles: state.plan.files.length,
  };
};

/** @deprecated Use saveGenerationState — kept for incremental migration of call sites. */
export const saveProjectPlan = (projectName: string, plan: AppPlan): void =>
  saveGenerationState(projectName, plan, "planned");

export const loadProjectPlan = (projectName: string): AppPlan | null =>
  loadGenerationState(projectName)?.plan ?? null;
