import { describe, it, expect } from "vitest";
import {
  getBareModuleName,
  isProjectFilePath,
  normalizeAliasSpecifier,
  isLocalProjectImport,
  isAliasImport,
  isRelativeImport,
  getNavigationLayoutPath,
  isSupportedNavigationType,
  isAutoGeneratedPlanFile,
} from "./generation-contract.js";

describe("generation-contract helpers", () => {
  describe("getBareModuleName", () => {
    it("keeps scope/name for scoped packages", () => {
      expect(getBareModuleName("@expo/vector-icons/Feather")).toBe("@expo/vector-icons");
      expect(getBareModuleName("@tamagui/core")).toBe("@tamagui/core");
    });

    it("returns the first segment for unscoped packages", () => {
      expect(getBareModuleName("react-native/Libraries/Text")).toBe("react-native");
      expect(getBareModuleName("zustand")).toBe("zustand");
    });

    it("returns the scope alone when there is no name", () => {
      expect(getBareModuleName("@scopeonly")).toBe("@scopeonly");
    });
  });

  describe("import classification", () => {
    it("detects alias, relative, and local imports", () => {
      expect(isAliasImport("@/ui")).toBe(true);
      expect(isAliasImport("react")).toBe(false);
      expect(isRelativeImport("./x")).toBe(true);
      expect(isRelativeImport("../x")).toBe(true);
      expect(isRelativeImport("@/x")).toBe(false);
      expect(isLocalProjectImport("@/ui")).toBe(true);
      expect(isLocalProjectImport("./x")).toBe(true);
      expect(isLocalProjectImport("tamagui")).toBe(false);
    });
  });

  describe("normalizeAliasSpecifier", () => {
    it("collapses the @/src/ double-prefix to @/", () => {
      expect(normalizeAliasSpecifier("@/src/components/Button")).toBe("@/components/Button");
    });

    it("leaves a normal alias untouched", () => {
      expect(normalizeAliasSpecifier("@/components/Button")).toBe("@/components/Button");
    });
  });

  describe("path predicates", () => {
    it("recognizes project file paths", () => {
      expect(isProjectFilePath("app/index.tsx")).toBe(true);
      expect(isProjectFilePath("src/lib/x.ts")).toBe(true);
      expect(isProjectFilePath("node_modules/x")).toBe(false);
      expect(isProjectFilePath("package.json")).toBe(false);
    });

    it("identifies auto-generated plan files", () => {
      expect(isAutoGeneratedPlanFile("app/_layout.tsx")).toBe(true);
      expect(isAutoGeneratedPlanFile("app/(tabs)/_layout.tsx")).toBe(true);
      expect(isAutoGeneratedPlanFile("app/index.tsx")).toBe(false);
    });
  });

  describe("navigation", () => {
    it("maps navigation types to layout paths", () => {
      expect(getNavigationLayoutPath("tabs")).toBe("app/(tabs)/_layout.tsx");
      expect(getNavigationLayoutPath("stack")).toBe("app/_layout.tsx");
    });

    it("validates supported navigation types", () => {
      expect(isSupportedNavigationType("tabs")).toBe(true);
      expect(isSupportedNavigationType("stack")).toBe(true);
      expect(isSupportedNavigationType("drawer")).toBe(false);
    });
  });
});
