// Create/iterate/revert orchestration — codegen+ship lives in generation-run + pipeline-codegen-phase.
import crypto from "crypto";
import fs from "fs";
import { broadcast } from "./event-bus.js";
import {
  startExpoClearCache,
  killExpo,
  getActivePort,
} from "../services/process-manager.js";
import { setPreviewPort } from "./event-bus.js";
import { getProjectPath } from "../services/file-manager.js";
import { planApp } from "./planner.js";
import { editProject } from "./editor.js";
import type { AppPlan } from "../schemas/app-plan.schema.js";
import {
  formatModelRoleLabel,
  resolveFixModel,
  resolvePlannerModel,
} from "./model-roles.js";
import { stripAutoGeneratedPlanFiles } from "./generation-contract.js";
import { autoHealPlanDependencies, dedupeProjectSlug } from "./pipeline-helpers.js";
import { formatPlanBriefForChat } from "./plan-brief.js";
import { saveGenerationState } from "./generation-state.js";
import { createPipelineEmitter } from "./pipeline-emitter.js";
import { executeCodegenRun } from "./generation-run.js";
import { triggerMetroBuild, waitForMetroReady } from "./metro-ready.js";
import type { PipelineContext } from "./pipeline-types.js";
import { createDefaultContext } from "./pipeline-types.js";
import { runProjectQualityGates } from "./pipeline-gates.js";
import { GIT_HASH_PATTERN, runGitCommand, gitCommit, getVersionNumber } from "./git.js";
import { markErrorReported } from "./reported-error.js";

export type { PipelineContext, GateResult } from "./pipeline-types.js";
export { createDefaultContext } from "./pipeline-types.js";
export { waitForBuildOutcome, runProjectQualityGates } from "./pipeline-gates.js";
export { runPolishStage } from "./pipeline-polish.js";
export { resumeProjectGeneration, ResumeGenerationError } from "./resume-generation.js";

interface CreateOptions {
  description: string;
  lmStudioUrl?: string;
  model?: string;
  plannerModel?: string;
  /** Model for build autofix (Metro/type errors). Falls back to `model`, then auto. */
  editorModel?: string;
  embeddingModel?: string;
  /** Smart semantic RAG (default true). */
  semanticRagEnabled?: boolean;
  /** Opt-in "Auto-polish" design loop after the first successful build (default false). */
  autoPolishEnabled?: boolean;
  /** Number of bounded polish passes (clamped 1..4 inside the loop; default 2). */
  autoPolishMaxPasses?: number;
  /** Override the LLM model used specifically for the auto-polish stage (empty = uses generation model). */
  polishModel?: string;
  temperature?: number;
  maxTokens?: number;
  /** Nucleus sampling (0–1). When undefined, the model default applies. */
  topP?: number;
  requestId?: string;
  onProjectNameResolved?: (projectName: string) => void;
}

interface CreateResult {
  projectName: string;
  port: number;
  plan: AppPlan;
  shipped: boolean;
  failureStage?: "gates" | "metro" | "preview";
}

interface IterateOptions {
  projectName: string;
  userRequest: string;
  chatHistory: Array<{ role: "user" | "assistant"; content: string }>;
  lmStudioUrl?: string;
  model?: string;
  /** Model for the editor (analyze + edit). Falls back to `model`, then auto. */
  editorModel?: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  requestId?: string;
}

interface IterateResult {
  appliedBlocks: number;
  failedBlocks: number;
  errors: string[];
}

export const createProject = async (
  options: CreateOptions,
  ctx: PipelineContext = createDefaultContext()
): Promise<CreateResult> => {
  try {
    return await _createProjectInner(options, ctx);
  } catch (error) {
    const scope = options.requestId ? { requestId: options.requestId } : {};
    const rawMessage = error instanceof Error ? error.message : String(error);
    const isLlmDown =
      rawMessage.includes("LLM_SERVER_DOWN") ||
      rawMessage.includes("LLM_NETWORK_ERROR");
    // Surface the actual failure reason to the chat before flipping status,
    // otherwise the client only sees a bare "error" with no explanation.
    ctx.broadcast({
      type: "system_error",
      error: isLlmDown ? `AI server disconnected: ${rawMessage}` : rawMessage,
      ...scope,
    });
    ctx.broadcast({
      type: "status",
      status: "error",
      ...scope,
    });
    // Mark the error so the queue's generic catch does not surface a duplicate
    // system_error: this handler already reported it with full context.
    markErrorReported(error);
    throw error;
  }
};

const _createProjectInner = async (
  options: CreateOptions,
  ctx: PipelineContext
): Promise<CreateResult> => {
  const {
    description,
    lmStudioUrl,
    model,
    plannerModel,
    editorModel,
    embeddingModel,
    semanticRagEnabled = true,
    autoPolishEnabled = false,
    autoPolishMaxPasses = 2,
    polishModel,
    temperature,
    maxTokens,
    topP,
    requestId,
    onProjectNameResolved,
  } = options;
  const plannerResolved = resolvePlannerModel(plannerModel, model);
  const { complete, createProjectFromCache: scaffoldFromCache } = ctx;

  const emitPreSlug = (message: Record<string, unknown>): void => {
    ctx.broadcast({
      ...message,
      ...(requestId ? { requestId } : {}),
    });
  };

  emitPreSlug({ type: "status", status: "planning" });
  emitPreSlug({
    type: "build_event",
    eventType: "moe_swap",
    message: formatModelRoleLabel("planner", plannerResolved),
  });

  const plan = await planApp({
    description,
    lmStudioUrl,
    model: plannerResolved,
    temperature,
    maxTokens,
    topP,
    complete,
    // Raw plan JSON is not streamed to chat — only saved to .appfactory/blueprint.json.
  });

  autoHealPlanDependencies(plan);
  stripAutoGeneratedPlanFiles(plan);

  const projectSlug = dedupeProjectSlug(plan.name, (slug) =>
    fs.existsSync(getProjectPath(slug)),
  );
  const finalizedPlan = { ...plan, name: projectSlug };

  onProjectNameResolved?.(projectSlug);

  const emitter = createPipelineEmitter(projectSlug, ctx.broadcast, requestId);
  emitter.emit({
    type: "plan_complete",
    plan: finalizedPlan,
    planBrief: formatPlanBriefForChat(plan),
    blueprintPath: ".appfactory/blueprint.json",
    briefPath: ".appfactory/blueprint-brief.md",
  });

  emitter.emit({ type: "status", status: "scaffolding" });

  const projectPath = await scaffoldFromCache(
    projectSlug,
    plan.displayName,
    plan.extraDependencies,
  );

  // Persist AFTER scaffold — createProjectFromCache rmSync wipes the project dir,
  // so an earlier save would delete blueprint + checkpoints (resume never worked).
  saveGenerationState(projectSlug, finalizedPlan, "scaffolded");
  emitter.emit({ type: "scaffold_complete", projectName: projectSlug });

  return executeCodegenRun({
    projectName: projectSlug,
    projectPath,
    plan: finalizedPlan,
    description,
    ctx,
    mode: "create",
    lmStudioUrl,
    model,
    editorModel,
    embeddingModel,
    semanticRagEnabled,
    autoPolishEnabled,
    autoPolishMaxPasses,
    polishModel,
    temperature,
    maxTokens,
    topP,
    requestId,
  });
};

export const iterateProject = async (
  options: IterateOptions
): Promise<IterateResult> => {
  try {
    return await _iterateProjectInner(options);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    const scopedMessage = {
      ...(options.requestId ? { requestId: options.requestId } : {}),
      projectName: options.projectName,
    };
    if (msg.includes("LLM_SERVER_DOWN") || msg.includes("LLM_NETWORK_ERROR")) {
      broadcast({
        type: "system_error",
        error: `AI server disconnected: ${msg}`,
        ...scopedMessage,
      });
    } else {
      broadcast({ type: "system_error", error: msg, ...scopedMessage });
    }
    broadcast({ type: "status", status: "error", ...scopedMessage });
    return { appliedBlocks: 0, failedBlocks: 0, errors: [msg] };
  }
};

const _iterateProjectInner = async (
  options: IterateOptions
): Promise<IterateResult> => {
  const { projectName, userRequest, chatHistory, lmStudioUrl, model, editorModel, temperature, maxTokens, topP, requestId } = options;
  const fixModel = resolveFixModel(editorModel, model);
  const projectPath = getProjectPath(projectName);
  const emitProject = (message: Record<string, unknown>): void => {
    broadcast({
      ...message,
      projectName,
      ...(requestId ? { requestId } : {}),
    });
  };

  emitProject({ type: "status", status: "analyzing" });
  emitProject({
    type: "build_event",
    eventType: "moe_swap",
    message: formatModelRoleLabel("fix", fixModel),
  });

  const result = await editProject({
    projectName,
    userRequest,
    chatHistory,
    lmStudioUrl,
    model: fixModel,
    temperature,
    maxTokens,
    topP,
    onThinking: (text) => emitProject({ type: "thinking", content: text }),
    onAnalysis: (action) =>
      emitProject({
        type: "analysis_complete",
        files: action.files,
        thinking: action.thinking,
      }),
    onBlock: (block) =>
      emitProject({ type: "block_applied", filepath: block.filepath, blockType: block.type }),
    onDiff: (filepath, before, after) =>
      emitProject({
        type: "file_diff",
        filepath,
        before: before.slice(0, 5000),
        after: after.slice(0, 5000),
      }),
  });

  if (result.appliedBlocks > 0) {
    emitProject({ type: "status", status: "validating" });

    const gateResult = await runProjectQualityGates(projectPath);
    if (!gateResult.success) {
      const combinedErrors = [...result.errors, ...gateResult.errors];
      const failedCount = Math.max(result.failedBlocks, gateResult.errors.length, 1);
      emitProject({
        type: "iteration_complete",
        applied: result.appliedBlocks,
        failed: failedCount,
        errors: combinedErrors,
      });
      emitProject({ type: "status", status: "error" });

      return {
        appliedBlocks: result.appliedBlocks,
        failedBlocks: failedCount,
        errors: combinedErrors,
      };
    }

    const versionNumber = getVersionNumber(projectPath);
    const commitHash = gitCommit(
      projectPath,
      `v${versionNumber}: ${userRequest.slice(0, 60)}`
    );

    if (commitHash) {
      emitProject({
        type: "version_created",
        version: versionNumber,
        hash: commitHash,
        description: userRequest,
      });
    }

    // HMR + warm-fetch is unreliable on Windows (Metro may serve a stale bundle while
    // on-disk files are already updated). Restart with a cleared cache — same pattern as
    // revertVersion — so the preview iframe always reflects the committed iteration.
    const previewPort = getActivePort(projectName);
    if (previewPort) {
      const buildId = crypto.randomUUID();
      emitProject({ type: "reloading_preview" });
      killExpo(projectName);
      emitProject({ type: "preview_status", previewStatus: "starting", buildId });

      const { port: restartedPort } = await startExpoClearCache(
        projectName,
        projectPath,
        previewPort,
        (event) => {
          emitProject({
            type: "build_event",
            buildId,
            eventType: event.type,
            message: event.message,
            error: event.error,
          });
        }
      );
      setPreviewPort(projectName, restartedPort);

      void triggerMetroBuild(restartedPort).catch((error) => {
        console.warn(
          `[Pipeline] triggerMetroBuild after iteration failed (ignored): ${
            error instanceof Error ? error.message : String(error)
          }`
        );
      });

      if (await waitForMetroReady(restartedPort, 60)) {
        emitProject({
          type: "preview_ready",
          buildId,
          port: restartedPort,
          proxyUrl: `/preview/${encodeURIComponent(projectName)}/`,
        });
        emitProject({ type: "preview_status", previewStatus: "ready", buildId });
        emitProject({
          type: "build_event",
          eventType: "build_success",
          message: "Metro bundle ready",
          buildId,
        });
      }
    }
  }

  emitProject({
    type: "iteration_complete",
    applied: result.appliedBlocks,
    failed: result.failedBlocks,
    errors: result.errors,
  });

  return {
    appliedBlocks: result.appliedBlocks,
    failedBlocks: result.failedBlocks,
    errors: result.errors,
  };
};

export const revertVersion = async (
  projectName: string,
  commitHash: string,
  _lmStudioUrl?: string,
  requestId?: string
): Promise<void> => {
  const projectPath = getProjectPath(projectName);
  const port = getActivePort(projectName);
  const emitProject = (message: Record<string, unknown>): void => {
    broadcast({
      ...message,
      projectName,
      ...(requestId ? { requestId } : {}),
    });
  };

  emitProject({ type: "reloading_preview" });

  killExpo(projectName);

  if (!GIT_HASH_PATTERN.test(commitHash)) {
    emitProject({
      type: "system_error",
      error: `Invalid commit hash: ${commitHash}`,
    });
    return;
  }

  try {
    runGitCommand(projectPath, ["clean", "-fd"]);
    runGitCommand(projectPath, ["checkout", commitHash, "--", "."]);
  } catch (err) {
    emitProject({
      type: "system_error",
      error: `Git revert failed: ${err instanceof Error ? err.message : "unknown"}`,
    });
    return;
  }

  if (port) {
    const buildId = crypto.randomUUID();
    emitProject({
      type: "preview_status",
      previewStatus: "starting",
      buildId,
    });
    // startExpoClearCache may bind a fresh port if the old one is still releasing,
    // so announce the actual port it bound, not the stale captured one.
    const { port: restartedPort } = await startExpoClearCache(
      projectName,
      projectPath,
      port,
      (event) => {
        emitProject({
          type: "build_event",
          buildId,
          eventType: event.type,
          message: event.message,
          error: event.error,
          previewStatus: "starting",
        });
      }
    );
    setPreviewPort(projectName, restartedPort);
    emitProject({
      type: "preview_ready",
      buildId,
      port: restartedPort,
      proxyUrl: `/preview/${encodeURIComponent(projectName)}/`,
    });
    emitProject({
      type: "preview_status",
      previewStatus: "ready",
      buildId,
    });
    emitProject({
      type: "status",
      status: "ready",
      previewStatus: "ready",
      buildId,
    });
  } else {
    emitProject({ type: "preview_status", previewStatus: "stopped", buildId: crypto.randomUUID() });
    emitProject({ type: "status", status: "ready" });
  }
};

// handleAutoFix removed — replaced by inline Build Verification Loop in createProject
// git helpers (runGitCommand/gitCommit/gitInit/getVersionNumber) live in ./git.ts
