// Adds contract-aware plan validation so invalid or unrecoverable planner JSON fails before generation starts.
import { streamCompletion, abortTask, type CompleteFn } from "../services/llm-proxy.js";
import { AppPlanSchema, type AppPlan } from "../schemas/app-plan.schema.js";
import { SYSTEM_PLANNER } from "../prompts/system-planner.js";
import { validateAppPlan } from "./project-validator.js";
import { stripAutoGeneratedPlanFiles } from "./generation-contract.js";
import { autoHealPlanDependencies } from "./pipeline-helpers.js";
import { safeJsonParse } from "./json-repair.js";
import { stripThinkingFromText } from "./strip-thinking.js";

// Hard ceiling so a slow model on an oversized prompt can never hang the Plan
// stage forever — a runaway plan becomes a clear error, not an infinite spinner.
const MAX_PLAN_DURATION_MS = 180_000;

interface PlannerOptions {
  description: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  lmStudioUrl?: string;
  model?: string;
  /** Model-completion seam; defaults to the real streamCompletion. */
  complete?: CompleteFn;
  onChunk?: (chunk: string) => void;
}

export interface PlanDepthAssessment {
  thin: boolean;
  reasons: string[];
}

const countByType = (plan: AppPlan, predicate: (path: string, type: string) => boolean): number =>
  plan.files.filter((file) => predicate(file.path, file.type)).length;

/**
 * Flags plans that are too shallow for a non-trivial request. Conservative on
 * purpose: a genuinely simple app (single screen, no list) is NOT flagged, so we
 * never force needless complexity. Triggers a single richer re-plan when a
 * multi-screen app lacks the data layer or reusable components a real product needs.
 */
// Auto-generated layout files (app/_layout.tsx, app/(tabs)/_layout.tsx) are written
// by the generator, not the model, so they must NOT count as screens — otherwise a
// simple one-screen app looks "multi-screen" and gets needlessly re-planned.
const isRealScreen = (path: string): boolean =>
  path.startsWith("app/") &&
  /\.(tsx|jsx)$/.test(path) &&
  !/(?:^|\/)_layout\.(?:tsx|jsx)$/.test(path);

export const assessPlanDepth = (plan: AppPlan): PlanDepthAssessment => {
  const screens = countByType(plan, (path) => isRealScreen(path));
  const components = countByType(plan, (path) => path.includes("/components/"));
  const stores = countByType(plan, (path) => path.includes("/stores/"));
  const reasons: string[] = [];

  // A multi-screen app with no state layer is almost always a hollow stub.
  if (screens >= 2 && stores === 0) {
    reasons.push("multiple screens but no Zustand store (no real data layer)");
  }
  // Several screens but no reusable components means monolithic, non-composed UI.
  if (screens >= 2 && components === 0) {
    reasons.push("multiple screens but zero reusable components (monolithic UI)");
  }
  // A clearly under-built app for anything beyond a single trivial screen.
  if (screens >= 3 && plan.files.length < 7) {
    reasons.push(`only ${plan.files.length} files for ${screens} screens (too shallow)`);
  }

  return { thin: reasons.length > 0, reasons };
};

const buildDepthFeedback = (reasons: string[]): string =>
  `\n\nThe previous plan looks shallow: ${reasons.join("; ")}. ` +
  `Add the missing pieces — a real data layer (src/types + a Zustand store with CRUD where it helps) ` +
  `and a few reusable components in src/components/ for repeated UI — plus the core list → detail → ` +
  `create/edit flow with empty/loading/error states. Keep it focused and buildable: quality over file count.`;

const PLAN_USER_PROMPT = (description: string): string =>
  `/no_think\nCreate an app plan for: ${description}\n\nRespond with ONLY a JSON object. No thinking, no explanation, no markdown.`;

const runPlannerOnce = async (
  options: PlannerOptions,
  userContent: string,
  streamChunks: boolean
): Promise<AppPlan> => {
  const { temperature = 0.3, maxTokens = 65536, topP, lmStudioUrl, model, onChunk, complete = streamCompletion } = options;

  const messages = [
    { role: "system" as const, content: SYSTEM_PLANNER },
    { role: "user" as const, content: userContent },
  ];

  // Own the task id so the timeout below can actually abort the HTTP request.
  // Without this, breaking the for-await only stops *reading* — LM Studio keeps
  // generating and the orphaned controller is dropped from the abort registry,
  // so even the user's Stop button can no longer cancel it.
  const taskId = crypto.randomUUID();
  let fullJson = "";
  const generator = await complete(messages, {
    temperature,
    maxTokens,
    topP,
    lmStudioUrl,
    model,
    taskId,
    responseFormat: { type: "json_object" },
  });

  let planChunkBuffer = "";
  let planLastSend = Date.now();
  const startedAt = Date.now();
  let timedOut = false;

  for await (const chunk of generator) {
    fullJson += chunk;
    if (Date.now() - startedAt > MAX_PLAN_DURATION_MS) {
      // Abort the live request BEFORE breaking: once the for-await teardown runs,
      // the controller is removed from the registry and can no longer be aborted.
      abortTask(taskId);
      timedOut = true;
      break;
    }
    if (!streamChunks) continue;
    planChunkBuffer += chunk;
    if (Date.now() - planLastSend > 100) {
      onChunk?.(planChunkBuffer);
      planChunkBuffer = "";
      planLastSend = Date.now();
    }
  }
  if (streamChunks && planChunkBuffer) onChunk?.(planChunkBuffer);

  if (timedOut) {
    throw new Error(
      `Planner exceeded ${MAX_PLAN_DURATION_MS / 1000}s — the model is producing an oversized plan. ` +
      `Try a simpler request or a faster model.`
    );
  }

  // Strip reasoning-model blocks (<think>, <thinking>, redacted_thinking) and
  // markdown fences via the shared utility so planner/editor behave identically.
  const trimmed = stripThinkingFromText(fullJson, { preferJson: true });

  const parsed = safeJsonParse(trimmed);
  if (parsed === null) {
    throw new Error(
      `Planner returned invalid JSON: unrecoverable parse error\n${trimmed.slice(0, 300)}`
    );
  }

  const result = AppPlanSchema.safeParse(parsed);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `${i.path.join(".")}: ${i.message}`)
      .join("; ");
    throw new Error(`Plan validation failed: ${issues}`);
  }

  // Heal before semantic validation — models often reference shared components
  // (e.g. EmptyState) in dependencies without listing them in plan.files.
  autoHealPlanDependencies(result.data);
  stripAutoGeneratedPlanFiles(result.data);

  const semanticIssues = validateAppPlan(result.data);
  if (semanticIssues.length > 0) {
    throw new Error(
      `Plan validation failed: ${semanticIssues
        .map((issue) => `${issue.filePath ?? "plan"}: ${issue.message}`)
        .join("; ")}`
    );
  }

  return result.data;
};

export const planApp = async (options: PlannerOptions): Promise<AppPlan> => {
  const { description } = options;
  const basePrompt = PLAN_USER_PROMPT(description);

  const plan = await runPlannerOnce(options, basePrompt, true);

  // One bounded re-plan if the first plan is hollow. It streams to the UI (so the
  // Plan stage shows live progress instead of appearing frozen) and falls back to
  // the first plan if it fails, so depth enforcement never breaks a working plan.
  const depth = assessPlanDepth(plan);
  if (!depth.thin) {
    return plan;
  }

  try {
    return await runPlannerOnce(options, basePrompt + buildDepthFeedback(depth.reasons), true);
  } catch {
    return plan;
  }
};
