// Persists plan artifacts: brief.md for models, blueprint.json for machines.
import fs from "fs";
import path from "path";
import { atomicWriteFileSync } from "./atomic-write.js";
import type { AppPlan } from "../schemas/app-plan.schema.js";
import { getProjectPath } from "../services/file-manager.js";
import { stripAutoGeneratedPlanFilesIfNeeded } from "./generation-contract.js";
import { formatPlanBriefForModels } from "./plan-brief.js";
import { warnCaught } from "./catch-log.js";

export const PLAN_ARTIFACT_DIR = ".appfactory";
export const PLAN_BLUEPRINT_FILE = "blueprint.json";
export const PLAN_BRIEF_FILE = "blueprint-brief.md";

export const getPlanBlueprintPath = (projectName: string): string =>
  path.join(getProjectPath(projectName), PLAN_ARTIFACT_DIR, PLAN_BLUEPRINT_FILE);

export const getPlanBriefPath = (projectName: string): string =>
  path.join(getProjectPath(projectName), PLAN_ARTIFACT_DIR, PLAN_BRIEF_FILE);

export const savePlanBlueprint = (projectName: string, plan: AppPlan): void => {
  atomicWriteFileSync(getPlanBlueprintPath(projectName), JSON.stringify(plan, null, 2));
  atomicWriteFileSync(getPlanBriefPath(projectName), formatPlanBriefForModels(plan));
};

export const loadPlanBrief = (projectName: string): string | null => {
  const filePath = getPlanBriefPath(projectName);
  if (!fs.existsSync(filePath)) {
    const plan = loadPlanBlueprint(projectName);
    return plan ? formatPlanBriefForModels(plan) : null;
  }
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    warnCaught("plan-artifact", error, "read plan brief");
    return null;
  }
};

const normalizeLoadedBlueprint = (
  projectName: string,
  plan: AppPlan,
  persistWhenChanged: boolean,
): AppPlan => {
  if (!stripAutoGeneratedPlanFilesIfNeeded(plan)) {
    return plan;
  }
  if (persistWhenChanged) {
    savePlanBlueprint(projectName, plan);
  }
  return plan;
};

export const loadPlanBlueprint = (projectName: string): AppPlan | null => {
  const filePath = getPlanBlueprintPath(projectName);
  if (!fs.existsSync(filePath)) {
    return null;
  }
  try {
    const plan = JSON.parse(fs.readFileSync(filePath, "utf8")) as AppPlan;
    return normalizeLoadedBlueprint(projectName, plan, true);
  } catch (error) {
    warnCaught("plan-artifact", error, "read plan blueprint");
    return null;
  }
};
