// Validates plans and generated projects against the shared contract before they reach build verification.
import fs from "fs";
import path from "path";
import type { AppPlan } from "../schemas/app-plan.schema.js";
import {
  getBareModuleName,
  getNavigationLayoutPath,
  ICON_CONTRACT,
  isAliasImport,
  isAutoGeneratedPlanFile,
  isLocalProjectImport,
  isProjectFilePath,
  isRelativeImport,
  REQUIRED_TEMPLATE_FILES,
  type SupportedNavigationType,
} from "./generation-contract.js";
import { type ExportContract } from "./context-builder.js";

export interface ValidationIssue {
  code: string;
  message: string;
  filePath?: string;
}

const SOURCE_FILE_PATTERN = /\.(ts|tsx|js|jsx)$/;

const IMPORT_PATTERN =
  /\b(?:import|export)\b[\s\S]*?\bfrom\s+["']([^"']+)["']|\bimport\s*\(\s*["']([^"']+)["']\s*\)/g;

const collectImportSpecifiers = (content: string): string[] => {
  const specifiers: string[] = [];

  for (const match of content.matchAll(IMPORT_PATTERN)) {
    const specifier = match[1] ?? match[2];
    if (specifier) {
      specifiers.push(specifier);
    }
  }

  return specifiers;
};

const dedupeIssues = (issues: ValidationIssue[]): ValidationIssue[] => {
  const seen = new Set<string>();
  return issues.filter((issue) => {
    const key = `${issue.code}:${issue.filePath ?? ""}:${issue.message}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
};

const resolveImportPath = (
  fromFilePath: string,
  specifier: string
): string | null => {
  if (isAliasImport(specifier)) {
    return `src/${specifier.slice(2)}`;
  }

  if (isRelativeImport(specifier)) {
    const normalized = path
      .normalize(path.join(path.dirname(fromFilePath), specifier))
      .replace(/\\/g, "/");

    return normalized;
  }

  return null;
};

const candidatePaths = (resolvedPath: string): string[] => {
  const normalized = resolvedPath.replace(/\\/g, "/");
  const hasExtension = /\.[a-z0-9]+$/i.test(normalized);

  if (hasExtension) {
    return [normalized];
  }

  return [
    `${normalized}.ts`,
    `${normalized}.tsx`,
    `${normalized}.js`,
    `${normalized}.jsx`,
    `${normalized}/index.ts`,
    `${normalized}/index.tsx`,
    `${normalized}/index.js`,
    `${normalized}/index.jsx`,
  ];
};

const fileExistsInProject = (projectPath: string, relativePath: string): boolean =>
  candidatePaths(relativePath).some((candidate) =>
    fs.existsSync(path.join(projectPath, candidate))
  );

const getProjectFiles = (projectPath: string): string[] => {
  const files: string[] = [];

  const walk = (currentPath: string): void => {
    const entries = fs.readdirSync(currentPath, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === "node_modules" || entry.name === ".git") {
        continue;
      }

      const fullPath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }

      files.push(path.relative(projectPath, fullPath).replace(/\\/g, "/"));
    }
  };

  walk(projectPath);
  return files;
};

const getNavigationFileIssues = (plan: AppPlan): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const fileSet = new Set(plan.files.map((file) => file.path));
  const navigationType: SupportedNavigationType = plan.navigation?.type ?? "stack";
  const layoutPath = getNavigationLayoutPath(navigationType);

  if (plan.files.some((file) => file.path === layoutPath)) {
    issues.push({
      code: "reserved_layout_path",
      filePath: layoutPath,
      message: `${layoutPath} is auto-generated and must not be included in plan.files`,
    });
  }

  for (const screen of plan.navigation?.screens ?? []) {
    if (!fileSet.has(screen.path)) {
      issues.push({
        code: "missing_navigation_screen",
        filePath: screen.path,
        message: `navigation screen "${screen.name}" must reference a file that exists in plan.files`,
      });
    }

    if (navigationType === "tabs" && !screen.path.startsWith("app/(tabs)/")) {
      issues.push({
        code: "invalid_tab_screen_path",
        filePath: screen.path,
        message: `tabs navigation screen "${screen.name}" must live under app/(tabs)/`,
      });
    }
  }

  return issues;
};

export const validateAppPlan = (plan: AppPlan): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const filePaths = new Set(plan.files.map((file) => file.path));

  if (filePaths.size !== plan.files.length) {
    issues.push({
      code: "duplicate_file_paths",
      message: "plan.files contains duplicate file paths",
    });
  }

  for (const file of plan.files) {
    for (const dependency of file.dependencies) {
      if (!isProjectFilePath(dependency) && !isAutoGeneratedPlanFile(dependency)) {
        issues.push({
          code: "invalid_dependency_reference",
          filePath: file.path,
          message: `dependency "${dependency}" must reference a project file path under app/ or src/`,
        });
        continue;
      }

      if (!filePaths.has(dependency) && !isAutoGeneratedPlanFile(dependency)) {
        issues.push({
          code: "missing_dependency_file",
          filePath: file.path,
          message: `dependency "${dependency}" is missing from plan.files`,
        });
      }
    }
  }

  issues.push(...getNavigationFileIssues(plan));

  return dedupeIssues(issues);
};

const readPackageNames = (projectPath: string): Set<string> => {
  const packageJsonPath = path.join(projectPath, "package.json");
  if (!fs.existsSync(packageJsonPath)) {
    return new Set<string>();
  }

  const parsed = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };

  return new Set([
    ...Object.keys(parsed.dependencies ?? {}),
    ...Object.keys(parsed.devDependencies ?? {}),
  ]);
};

const validateSourceFileImports = (
  projectPath: string,
  filePath: string,
  packageNames: Set<string>
): ValidationIssue[] => {
  const fullPath = path.join(projectPath, filePath);
  const content = fs.readFileSync(fullPath, "utf-8");
  const issues: ValidationIssue[] = [];

  for (const originalSpecifier of collectImportSpecifiers(content)) {
    const specifier = originalSpecifier.trim();

    if (specifier.startsWith("@/src/")) {
      issues.push({
        code: "double_src_alias",
        filePath,
        message: `import "${specifier}" uses the invalid @/src/ alias pattern`,
      });
      continue;
    }

    if (specifier === ICON_CONTRACT.packageName) {
      issues.push({
        code: "base_vector_icons_import",
        filePath,
        message: `import "${specifier}" should use ${ICON_CONTRACT.defaultImportPath} or another explicit icon subpath`,
      });
      continue;
    }

    if (specifier === "expo-router/tabs") {
      issues.push({
        code: "invalid_expo_router_tabs_import",
        filePath,
        message: `import "${specifier}" is invalid; use "expo-router"`,
      });
      continue;
    }

    if (isLocalProjectImport(specifier)) {
      const resolved = resolveImportPath(filePath, specifier);
      if (!resolved || !fileExistsInProject(projectPath, resolved)) {
        issues.push({
          code: "missing_local_import",
          filePath,
          message: `import "${specifier}" cannot be resolved from ${filePath}`,
        });
      }
      continue;
    }

    const bareModuleName = getBareModuleName(specifier);
    if (!packageNames.has(bareModuleName)) {
      issues.push({
        code: "missing_package_dependency",
        filePath,
        message: `import "${specifier}" requires missing dependency "${bareModuleName}"`,
      });
    }
  }

  return issues;
};

const detectNavigationType = (projectFiles: Set<string>): SupportedNavigationType =>
  projectFiles.has("app/(tabs)/_layout.tsx") ? "tabs" : "stack";

export const validateGeneratedProject = (
  projectPath: string,
  navigationType?: SupportedNavigationType
): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const projectFiles = getProjectFiles(projectPath);
  const packageNames = readPackageNames(projectPath);
  const projectFileSet = new Set(projectFiles);
  const resolvedNavigationType = navigationType ?? detectNavigationType(projectFileSet);
  const requiredFiles = new Set<string>(REQUIRED_TEMPLATE_FILES);
  requiredFiles.add(getNavigationLayoutPath(resolvedNavigationType));

  for (const requiredFile of requiredFiles) {
    if (!projectFileSet.has(requiredFile)) {
      issues.push({
        code: "missing_required_file",
        filePath: requiredFile,
        message: `required scaffold file "${requiredFile}" is missing`,
      });
    }
  }

  for (const filePath of projectFiles) {
    if (!SOURCE_FILE_PATTERN.test(filePath)) {
      continue;
    }

    issues.push(...validateSourceFileImports(projectPath, filePath, packageNames));
  }

  return dedupeIssues(issues);
};

// ── JSON Contract Validation ──

export interface ContractViolation {
  filePath: string;
  dependencyPath: string;
  code: "default_import_mismatch" | "named_import_mismatch" | "invalid_destructured_key";
  message: string;
  expected: string;
  actual: string;
}

const IMPORT_SHAPE_REGEX = /import\s+(?:(\w+)\s*,?\s*)?(?:\{([^}]+)\})?\s+from\s+["']([^"']+)["']/g;
const DESTRUCTURE_HOOK_REGEX = /const\s+\{\s*([^}]+)\s*\}\s*=\s*(use[A-Za-z0-9_]+)\s*\(/g;

/** Extract interface/type keys from store source code via regex (fallback when ts-morph fails) */
const extractStoreKeysFromSource = (
  projectPath: string,
  storePath: string,
): string[] => {
  try {
    const fs = require("fs");
    const fullPath = require("path").join(projectPath, storePath);
    if (!fs.existsSync(fullPath)) return [];
    const content = fs.readFileSync(fullPath, "utf-8");

    // Match interface body: interface XStore { key1: type; key2: type; ... }
    const ifaceMatch = content.match(/interface\s+\w+(?:Store|State)\s*\{([^}]+)\}/);
    if (ifaceMatch) {
      const body = ifaceMatch[1];
      return body.split(/[;\n]/).map((line: string) => line.trim().split(/[:(]/)[0].trim()).filter(Boolean);
    }
  } catch { /* ignore */ }
  return [];
};

/** Validate that generated files respect export contracts of their dependencies */
export const validateFileContracts = (
  fileContent: string,
  filePath: string,
  contracts: Record<string, ExportContract[]>,
): ContractViolation[] => {
  const violations: ContractViolation[] = [];
  const allContracts = Object.values(contracts).flat();

  let match: RegExpExecArray | null;
  IMPORT_SHAPE_REGEX.lastIndex = 0;

  while ((match = IMPORT_SHAPE_REGEX.exec(fileContent)) !== null) {
    const defaultImport = match[1];
    const namedImports = match[2];
    const modulePath = match[3];

    if (defaultImport) {
      const contract = allContracts.find((c) => c.name === defaultImport);
      if (contract && !contract.isDefaultExport) {
        violations.push({
          filePath, dependencyPath: modulePath, code: "named_import_mismatch",
          message: `'${defaultImport}' imported as default but is a named export`,
          expected: `import { ${contract.name} } from "${modulePath}"`,
          actual: `import ${defaultImport} from "${modulePath}"`,
        });
      }
    }

    if (namedImports) {
      for (const raw of namedImports.split(",")) {
        const imp = raw.trim().split(/\s+as\s+/)[0].trim();
        if (!imp) continue;
        const contract = allContracts.find((c) => c.name === imp);
        if (contract && contract.isDefaultExport) {
          violations.push({
            filePath, dependencyPath: modulePath, code: "default_import_mismatch",
            message: `'${imp}' imported as named but is a default export`,
            expected: `import ${imp} from "${modulePath}"`,
            actual: `import { ${imp} } from "${modulePath}"`,
          });
        }
      }
    }
  }

  DESTRUCTURE_HOOK_REGEX.lastIndex = 0;

  while ((match = DESTRUCTURE_HOOK_REGEX.exec(fileContent)) !== null) {
    const keys = match[1];
    const hookName = match[2];
    let contract = allContracts.find((c) => c.name === hookName);

    // Fallback chain for Zustand store hooks
    let validKeys = contract?.returnObjectKeys ?? [];

    if (validKeys.length === 0) {
      // Try 1: find store contract by hook name
      const storeImportMatch = fileContent.match(
        new RegExp(`import.*${hookName}.*from\\s+["']([^"']+)["']`)
      );
      if (storeImportMatch) {
        const importPath = storeImportMatch[1].replace("@/", "src/").replace(/^\.\//, "");
        const allFiles = Object.keys(contracts);
        const storeFile = allFiles.find((f) =>
          f.includes(importPath.split("/").pop()?.replace(/\.ts$/, "") ?? "")
        );
        if (storeFile) {
          for (const sc of (contracts[storeFile] ?? [])) {
            if (sc.returnObjectKeys.length > 0) {
              validKeys = sc.returnObjectKeys;
              break;
            }
          }
        }

        // Try 2: read store source file and extract interface keys via regex
        if (validKeys.length === 0 && storeFile) {
          const storeKeys = extractStoreKeysFromSource("", storeFile);
          if (storeKeys.length > 0) validKeys = storeKeys;
        }
      }
    }

    if (validKeys.length > 0) {
      const destructuredKeys = keys.split(",").map((k) => k.split(":")[0].trim()).filter(Boolean);
      for (const key of destructuredKeys) {
        if (!validKeys.includes(key)) {
          violations.push({
            filePath, dependencyPath: "", code: "invalid_destructured_key",
            message: `Hook '${hookName}' does not return key '${key}'. Available: [${validKeys.join(", ")}]`,
            expected: `{ ${validKeys.join(", ")} }`,
            actual: `{ ${destructuredKeys.join(", ")} }`,
          });
        }
      }
    }
  }

  return violations;
};
