// Validates plans and generated projects against the shared contract before they reach build verification.
import fs from "fs";
import path from "path";
import { Project, ScriptKind, SyntaxKind, type InterfaceDeclaration } from "ts-morph";
import type { AppPlan } from "../schemas/app-plan.schema.js";
import { warnCaught } from "./catch-log.js";
import {
  AUTO_GENERATED_PLAN_FILES,
  getBareModuleName,
  getNavigationLayoutPath,
  ICON_CONTRACT,
  isAliasImport,
  isAutoGeneratedPlanFile,
  isLocalProjectImport,
  isProjectFilePath,
  isRelativeImport,
  REQUIRED_TEMPLATE_FILES,
  type SupportedNavigationType,
} from "./generation-contract.js";
import { type ExportContract } from "./context-builder.js";

export interface ValidationIssue {
  code: string;
  message: string;
  filePath?: string;
}

const SOURCE_FILE_PATTERN = /\.(ts|tsx|js|jsx)$/;

const scriptKindForPath = (filePath: string): ScriptKind => {
  if (filePath.endsWith(".tsx")) return ScriptKind.TSX;
  if (filePath.endsWith(".jsx")) return ScriptKind.JSX;
  if (filePath.endsWith(".js")) return ScriptKind.JS;
  return ScriptKind.TS;
};

const collectImportSpecifiers = (content: string, filePath: string): string[] => {
  const specifiers: string[] = [];
  const project = new Project({ useInMemoryFileSystem: true, compilerOptions: { jsx: 2 } });
  const sourceFile = project.createSourceFile(filePath, content, {
    overwrite: true,
    scriptKind: scriptKindForPath(filePath),
  });

  for (const decl of sourceFile.getImportDeclarations()) {
    const specifier = decl.getModuleSpecifierValue();
    if (specifier) {
      specifiers.push(specifier);
    }
  }

  for (const decl of sourceFile.getExportDeclarations()) {
    const specifier = decl.getModuleSpecifierValue();
    if (specifier) {
      specifiers.push(specifier);
    }
  }

  sourceFile.forEachDescendant((node) => {
    if (!node.isKind(SyntaxKind.CallExpression)) {
      return;
    }
    const call = node.asKindOrThrow(SyntaxKind.CallExpression);
    if (!call.getExpression().isKind(SyntaxKind.ImportKeyword)) {
      return;
    }
    const arg = call.getArguments()[0];
    if (arg?.isKind(SyntaxKind.StringLiteral)) {
      specifiers.push(arg.getLiteralText());
    }
  });

  return specifiers;
};

const dedupeIssues = (issues: ValidationIssue[]): ValidationIssue[] => {
  const seen = new Set<string>();
  return issues.filter((issue) => {
    const key = `${issue.code}:${issue.filePath ?? ""}:${issue.message}`;
    if (seen.has(key)) {
      return false;
    }
    seen.add(key);
    return true;
  });
};

const resolveImportPath = (
  fromFilePath: string,
  specifier: string
): string | null => {
  if (isAliasImport(specifier)) {
    return `src/${specifier.slice(2)}`;
  }

  if (isRelativeImport(specifier)) {
    const normalized = path
      .normalize(path.join(path.dirname(fromFilePath), specifier))
      .replace(/\\/g, "/");

    return normalized;
  }

  return null;
};

const candidatePaths = (resolvedPath: string): string[] => {
  const normalized = resolvedPath.replace(/\\/g, "/");
  const hasExtension = /\.[a-z0-9]+$/i.test(normalized);

  if (hasExtension) {
    return [normalized];
  }

  return [
    `${normalized}.ts`,
    `${normalized}.tsx`,
    `${normalized}.js`,
    `${normalized}.jsx`,
    `${normalized}/index.ts`,
    `${normalized}/index.tsx`,
    `${normalized}/index.js`,
    `${normalized}/index.jsx`,
  ];
};

const fileExistsInProject = (projectPath: string, relativePath: string): boolean =>
  candidatePaths(relativePath).some((candidate) =>
    fs.existsSync(path.join(projectPath, candidate))
  );

const getProjectFiles = (projectPath: string): string[] => {
  const files: string[] = [];

  const walk = (currentPath: string): void => {
    const entries = fs.readdirSync(currentPath, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === "node_modules" || entry.name === ".git") {
        continue;
      }

      const fullPath = path.join(currentPath, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
        continue;
      }

      files.push(path.relative(projectPath, fullPath).replace(/\\/g, "/"));
    }
  };

  walk(projectPath);
  return files;
};

const getNavigationFileIssues = (plan: AppPlan): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const fileSet = new Set(plan.files.map((file) => file.path));
  const navigationType: SupportedNavigationType = plan.navigation?.type ?? "stack";
  for (const layoutPath of AUTO_GENERATED_PLAN_FILES) {
    if (plan.files.some((file) => file.path === layoutPath)) {
      issues.push({
        code: "reserved_layout_path",
        filePath: layoutPath,
        message: `${layoutPath} is auto-generated and must not be included in plan.files`,
      });
    }
  }

  for (const screen of plan.navigation?.screens ?? []) {
    if (!fileSet.has(screen.path)) {
      issues.push({
        code: "missing_navigation_screen",
        filePath: screen.path,
        message: `navigation screen "${screen.name}" must reference a file that exists in plan.files`,
      });
    }

    if (navigationType === "tabs" && !screen.path.startsWith("app/(tabs)/")) {
      issues.push({
        code: "invalid_tab_screen_path",
        filePath: screen.path,
        message: `tabs navigation screen "${screen.name}" must live under app/(tabs)/`,
      });
    }
  }

  return issues;
};

export const validateAppPlan = (plan: AppPlan): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const filePaths = new Set(plan.files.map((file) => file.path));

  if (filePaths.size !== plan.files.length) {
    issues.push({
      code: "duplicate_file_paths",
      message: "plan.files contains duplicate file paths",
    });
  }

  // Tolerant lookup: index every planned file by its exact path AND its
  // extension-stripped form so a dependency spelled without ".ts"/"/index" (the
  // natural form models emit, e.g. "src/stores/itemStore") still resolves.
  const planFileLookup = new Set<string>();
  for (const file of plan.files) {
    planFileLookup.add(file.path);
    planFileLookup.add(file.path.replace(SOURCE_FILE_PATTERN, ""));
  }
  const dependencyInPlan = (dependency: string): boolean =>
    planFileLookup.has(dependency) ||
    planFileLookup.has(dependency.replace(SOURCE_FILE_PATTERN, "")) ||
    candidatePaths(dependency).some((candidate) => planFileLookup.has(candidate));

  for (const file of plan.files) {
    for (const dependency of file.dependencies) {
      // Bare npm package name (no slash, no dot) — not a project path.
      if (!dependency.includes("/") && !dependency.includes(".")) {
        continue;
      }
      // Scoped npm package (@scope/name) that is NOT a path alias (@/...).
      if (dependency.startsWith("@") && !isAliasImport(dependency)) {
        continue;
      }

      // Normalize a "@/..." alias to its project path so alias-form deps are
      // validated symmetrically with src/ deps (they were skipped entirely before,
      // hiding genuinely missing alias dependencies).
      const normalized = isAliasImport(dependency)
        ? `src/${dependency.slice(2)}`
        : dependency;

      if (!isProjectFilePath(normalized) && !isAutoGeneratedPlanFile(normalized)) {
        issues.push({
          code: "invalid_dependency_reference",
          filePath: file.path,
          message: `dependency "${dependency}" must reference a project file path under app/ or src/`,
        });
        continue;
      }

      if (!isAutoGeneratedPlanFile(normalized) && !dependencyInPlan(normalized)) {
        issues.push({
          code: "missing_dependency_file",
          filePath: file.path,
          message: `dependency "${dependency}" is missing from plan.files`,
        });
      }
    }
  }

  issues.push(...getNavigationFileIssues(plan));

  return dedupeIssues(issues);
};

const readPackageNames = (projectPath: string): Set<string> => {
  const packageJsonPath = path.join(projectPath, "package.json");
  if (!fs.existsSync(packageJsonPath)) {
    return new Set<string>();
  }

  let parsed: { dependencies?: Record<string, string>; devDependencies?: Record<string, string> };
  try {
    parsed = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
  } catch (error) {
    warnCaught("project-validator", error, "read package.json dependencies");
    return new Set<string>();
  }

  return new Set([
    ...Object.keys(parsed.dependencies ?? {}),
    ...Object.keys(parsed.devDependencies ?? {}),
  ]);
};

const validateSourceFileImports = (
  projectPath: string,
  filePath: string,
  packageNames: Set<string>
): ValidationIssue[] => {
  const fullPath = path.join(projectPath, filePath);
  let content: string;
  try {
    content = fs.readFileSync(fullPath, "utf-8");
  } catch (error) {
    warnCaught("project-validator", error, `read source file ${filePath}`);
    return [];
  }
  const issues: ValidationIssue[] = [];

  for (const originalSpecifier of collectImportSpecifiers(content, filePath)) {
    const specifier = originalSpecifier.trim();

    if (specifier.startsWith("@/src/")) {
      issues.push({
        code: "double_src_alias",
        filePath,
        message: `import "${specifier}" uses the invalid @/src/ alias pattern`,
      });
      continue;
    }

    if (specifier === ICON_CONTRACT.packageName) {
      issues.push({
        code: "base_vector_icons_import",
        filePath,
        message: `import "${specifier}" should use ${ICON_CONTRACT.defaultImportPath} or another explicit icon subpath`,
      });
      continue;
    }

    if (specifier === "expo-router/tabs") {
      issues.push({
        code: "invalid_expo_router_tabs_import",
        filePath,
        message: `import "${specifier}" is invalid; use "expo-router"`,
      });
      continue;
    }

    if (isLocalProjectImport(specifier)) {
      const resolved = resolveImportPath(filePath, specifier);
      // Root-level config files (tamagui.config, etc.) are boilerplate — always present
      if (resolved && !resolved.startsWith("src/") && !resolved.startsWith("app/")) {
        continue;
      }
      if (!resolved || !fileExistsInProject(projectPath, resolved)) {
        issues.push({
          code: "missing_local_import",
          filePath,
          message: `import "${specifier}" cannot be resolved from ${filePath}`,
        });
      }
      continue;
    }

    const bareModuleName = getBareModuleName(specifier);
    if (!packageNames.has(bareModuleName)) {
      issues.push({
        code: "missing_package_dependency",
        filePath,
        message: `import "${specifier}" requires missing dependency "${bareModuleName}"`,
      });
    }
  }

  return issues;
};

const detectNavigationType = (projectFiles: Set<string>): SupportedNavigationType =>
  projectFiles.has("app/(tabs)/_layout.tsx") ? "tabs" : "stack";

export const validateGeneratedProject = (
  projectPath: string,
  navigationType?: SupportedNavigationType
): ValidationIssue[] => {
  const issues: ValidationIssue[] = [];
  const projectFiles = getProjectFiles(projectPath);
  const packageNames = readPackageNames(projectPath);
  const projectFileSet = new Set(projectFiles);
  const resolvedNavigationType = navigationType ?? detectNavigationType(projectFileSet);
  const requiredFiles = new Set<string>(REQUIRED_TEMPLATE_FILES);
  requiredFiles.add(getNavigationLayoutPath(resolvedNavigationType));

  for (const requiredFile of requiredFiles) {
    if (!projectFileSet.has(requiredFile)) {
      issues.push({
        code: "missing_required_file",
        filePath: requiredFile,
        message: `required scaffold file "${requiredFile}" is missing`,
      });
    }
  }

  for (const filePath of projectFiles) {
    if (!SOURCE_FILE_PATTERN.test(filePath)) {
      continue;
    }

    issues.push(...validateSourceFileImports(projectPath, filePath, packageNames));
  }

  return dedupeIssues(issues);
};

// ── JSON Contract Validation ──

export interface ContractViolation {
  filePath: string;
  dependencyPath: string;
  code: "default_import_mismatch" | "named_import_mismatch" | "invalid_destructured_key";
  message: string;
  expected: string;
  actual: string;
}

const DESTRUCTURE_HOOK_REGEX = /const\s+\{\s*([^}]+)\s*\}\s*=\s*(use[A-Za-z0-9_]+)\s*\(/g;

const collectTopLevelInterfaceKeys = (iface: InterfaceDeclaration): string[] =>
  iface.getProperties().map((property) => property.getName());

/** Extract store interface keys via ts-morph (handles nested property types in values). */
const extractStoreKeysFromSource = (
  projectPath: string,
  storePath: string,
): string[] => {
  try {
    const fullPath = path.join(projectPath, storePath);
    if (!fs.existsSync(fullPath)) {
      return [];
    }
    const content = fs.readFileSync(fullPath, "utf-8");
    const project = new Project({ useInMemoryFileSystem: true, compilerOptions: { jsx: 2 } });
    const sourceFile = project.createSourceFile(storePath, content, {
      overwrite: true,
      scriptKind: scriptKindForPath(storePath),
    });

    // Union EVERY store-shaped interface, not just the first. The dominant Zustand
    // idiom splits state and actions (`create<CounterState & CounterActions>(...)`),
    // so reading only the first `*State` interface dropped all the action keys and
    // produced false `invalid_destructured_key` violations on correct stores.
    const storeIfaces = sourceFile
      .getInterfaces()
      .filter((iface) => /(?:Store|State|Actions|Slice)$/.test(iface.getName()));
    if (storeIfaces.length > 0) {
      const keys = new Set<string>();
      for (const iface of storeIfaces) {
        for (const key of collectTopLevelInterfaceKeys(iface)) keys.add(key);
      }
      return [...keys];
    }

    const fallback = sourceFile.getInterfaces().find((iface) => iface.getProperties().length >= 3);
    return fallback ? collectTopLevelInterfaceKeys(fallback) : [];
  } catch (error) {
    warnCaught("project-validator", error, "extract store interface keys");
    return [];
  }
};

/**
 * Resolve an import specifier (from `fromFilePath`) to the export contracts of the
 * module it actually points at, or [] when it resolves to no KNOWN generated file
 * (a node_modules package, or a scaffold barrel like "@/ui"/"@/services/db" that is
 * not in the generated-contracts map).
 *
 * This is what makes contract matching PATH-SCOPED: a symbol name only matches the
 * contract of the module that is actually imported. The previous name-only matching
 * collided a local default `Button` with the named `@/ui` `Button` and silently
 * rewrote correct code into a typecheck failure.
 */
const contractsForSpecifier = (
  contracts: Record<string, ExportContract[]>,
  fromFilePath: string,
  specifier: string,
): ExportContract[] => {
  const resolved = resolveImportPath(fromFilePath, specifier);
  if (!resolved) return [];
  for (const candidate of candidatePaths(resolved)) {
    if (contracts[candidate]) return contracts[candidate];
  }
  return [];
};

// Matches one import statement, capturing: type-only modifier, a solo default name,
// a braced named group, and the module specifier.
const IMPORT_STATEMENT_REGEX =
  /import\s+(type\s+)?(?:(\w+)\s*,?\s*)?(?:\{([^}]+)\})?\s+from\s+["']([^"']+)["']/g;

/**
 * Auto-heal default/named import-shape mismatches by rewriting the file on disk.
 * PATH-SCOPED: only rewrites when the import's RESOLVED module owns a contract for
 * that exact name with the opposite shape — never because a same-named symbol exists
 * in some other module. Returns the healed content (or the original if unchanged).
 */
export const autoHealImportContracts = (
  fileContent: string,
  contracts: Record<string, ExportContract[]>,
  fromFilePath = "",
): string =>
  fileContent.replace(
    IMPORT_STATEMENT_REGEX,
    (full, typeKw, defaultName, namedGroup, modulePath) => {
      if (typeKw) return full; // type-only imports have no runtime shape to heal
      const moduleContracts = contractsForSpecifier(contracts, fromFilePath, modulePath);
      if (moduleContracts.length === 0) return full;

      // import X from "path" → import { X } from "path"  (X is actually a named export)
      if (defaultName && !namedGroup) {
        const contract = moduleContracts.find((c) => c.name === defaultName);
        if (contract && !contract.isDefaultExport) {
          return `import { ${defaultName} } from "${modulePath}"`;
        }
      }

      // import { X } from "path" → import X from "path"  (X is actually the default export)
      if (!defaultName && namedGroup) {
        const names = namedGroup
          .split(",")
          .map((n: string) => n.trim().split(/\s+as\s+/)[0].trim())
          .filter(Boolean);
        if (names.length === 1) {
          const contract = moduleContracts.find((c) => c.name === names[0]);
          if (contract && contract.isDefaultExport) {
            return `import ${names[0]} from "${modulePath}"`;
          }
        }
      }

      return full;
    },
  );

/** Validate that generated files respect export contracts of their dependencies */
export const validateFileContracts = (
  fileContent: string,
  filePath: string,
  contracts: Record<string, ExportContract[]>,
  projectPath = "",
): ContractViolation[] => {
  const violations: ContractViolation[] = [];

  let match: RegExpExecArray | null;
  IMPORT_STATEMENT_REGEX.lastIndex = 0;

  while ((match = IMPORT_STATEMENT_REGEX.exec(fileContent)) !== null) {
    if (match[1]) continue; // `import type {...}` — erased at runtime, no shape to validate
    const defaultImport = match[2];
    const namedImports = match[3];
    const modulePath = match[4];

    // PATH-SCOPED: only compare against the contract of the module ACTUALLY imported,
    // so a local symbol never gets flagged because a same-named export lives elsewhere.
    const moduleContracts = contractsForSpecifier(contracts, filePath, modulePath);

    if (defaultImport) {
      const contract = moduleContracts.find((c) => c.name === defaultImport);
      if (contract && !contract.isDefaultExport) {
        violations.push({
          filePath, dependencyPath: modulePath, code: "named_import_mismatch",
          message: `'${defaultImport}' imported as default but is a named export`,
          expected: `import { ${contract.name} } from "${modulePath}"`,
          actual: `import ${defaultImport} from "${modulePath}"`,
        });
      }
    }

    if (namedImports) {
      for (const raw of namedImports.split(",")) {
        const imp = raw.trim().split(/\s+as\s+/)[0].trim();
        if (!imp) continue;
        const contract = moduleContracts.find((c) => c.name === imp);
        if (contract && contract.isDefaultExport) {
          violations.push({
            filePath, dependencyPath: modulePath, code: "default_import_mismatch",
            message: `'${imp}' imported as named but is a default export`,
            expected: `import ${imp} from "${modulePath}"`,
            actual: `import { ${imp} } from "${modulePath}"`,
          });
        }
      }
    }
  }

  DESTRUCTURE_HOOK_REGEX.lastIndex = 0;

  while ((match = DESTRUCTURE_HOOK_REGEX.exec(fileContent)) !== null) {
    const keys = match[1];
    const hookName = match[2];
    // PATH-SCOPED: resolve the hook's OWNING module via its import specifier (not a
    // name-only lookup across ALL contracts), so two stores/hooks that share a name —
    // or a library hook (useWindowDimensions) whose name collides with a store — no
    // longer produce a false invalid_destructured_key.
    let validKeys: string[] = [];
    const hookImport = fileContent.match(
      new RegExp(`import\\s+(?:\\{[^}]*\\b${hookName}\\b[^}]*\\}|${hookName})\\s+from\\s+["']([^"']+)["']`)
    );
    if (hookImport) {
      const moduleContracts = contractsForSpecifier(contracts, filePath, hookImport[1]);
      const hookContract = moduleContracts.find((c) => c.name === hookName);
      if (hookContract && hookContract.returnObjectKeys.length > 0) {
        validKeys = hookContract.returnObjectKeys;
      } else {
        // A contract exists but its keys weren't extracted (e.g. a split
        // create<State & Actions> store) → read the RESOLVED store file directly.
        const resolved = resolveImportPath(filePath, hookImport[1]);
        const storeFile = resolved
          ? candidatePaths(resolved).find((candidate) => contracts[candidate])
          : undefined;
        if (storeFile) {
          const storeKeys = extractStoreKeysFromSource(projectPath, storeFile);
          if (storeKeys.length > 0) validKeys = storeKeys;
        }
      }
    } else {
      // Hook is not imported (defined locally in this file) → only a local contract counts.
      const localContract = (contracts[filePath] ?? []).find((c) => c.name === hookName);
      validKeys = localContract?.returnObjectKeys ?? [];
    }

    if (validKeys.length > 0) {
      const destructuredKeys = keys.split(",").map((k) => k.split(":")[0].trim()).filter(Boolean);
      for (const key of destructuredKeys) {
        if (!validKeys.includes(key)) {
          violations.push({
            filePath, dependencyPath: "", code: "invalid_destructured_key",
            message: `Hook '${hookName}' does not return key '${key}'. Available: [${validKeys.join(", ")}]`,
            expected: `{ ${validKeys.join(", ")} }`,
            actual: `{ ${destructuredKeys.join(", ")} }`,
          });
        }
      }
    }
  }

  return violations;
};
